m=bench;
f=bsearch(arr:[i64];target:i64):i64{
  let lo=mut.0;
  let hi=mut.arr.len-1;
  lp(let dummy=0;lo<hi+1;dummy=0){
    let mid=lo+(hi-lo)/2;
    if(arr[mid]<target){
      lo=mid+1
    }el{
      if(arr[mid]>target){
        hi=mid-1
      }el{
        <mid
      }
    }
  };
  <0-1
};
f=main():i64{
  let a=[2;4;6;8;10;12;14;16;18;20;22;24;26;28;30;32;34;36;38;40;42;44;46;48;50];
  let found=mut.0;
  lp(let r=0;r<1000000;r=r+1){
    found=found+bsearch(a;30)
  };
  <found
};
