m=mortgage.web.app;
i=router:std.router;
i=file:std.file;
i=idx:mortgage.web.index;
i=calc:mortgage.web.calculate;


f=statichandler(req:i64):i64{
  let content=mt file.read("static/style.css") {
    $ok:v v;
    $err:e <router.notfound("file not found")
  };
  <router.css(content)
};


f=main():i64{
  let r=router.new();
  router.get(r;"/";&idx.handler);
  router.post(r;"/calculate";&calc.handler);
  router.get(r;"/static/style.css";&statichandler);
  router.serve(r;"0.0.0.0";8080);
  <0
};
