m=mortgage.web.index;
i=http:std.http;
i=tpl:std.template;
i=str:std.str;


f=handler(req:i64):i64{
  let vars=tpl.vars(@("title":"Mortgage Calculator"));
  let layout=mt tpl.renderfile("templates/layout.tkt";vars) {
    $ok:v v;
    $err:e <http.res.err("template error")
  };
  let body=mt tpl.renderfile("templates/index.tkt";tpl.vars(@())) {
    $ok:v v;
    $err:e <http.res.err("template error")
  };
  let page=str.replace(layout;"{{content}}";body);
  <http.res.ok(page)
};
