m=tw;
i=io:std.io;

i=s:std.str;

f=main():$i64 {
  let target=s.trim(io.readln());
  let taboos=mut.@($str);
  lp (1) {
    let l=io.readln();
    if (s.len(l)==0) {
      br
    };
    let t=s.trim(l);
    if (s.len(t)==0) {
      br
    };
    taboos=taboos.append(t)
  };
  let db=s.builder();
  lp (1) {
    let l=io.readln();
    if (s.len(l)==0) {
      br
    };
    s.add(db; l)
  };
  let words=s.split(s.upper(s.build(db)); " ");
  let cleanWords=mut.@($str);
  lp (let i=0; i<words.len(); i=i+1) {
    let w=s.trim(words.get(i));
    let cb=s.builder();
    lp (let j=0; j<s.len(w); j=j+1) {
      let c=s.slice(w; j; j+1);
      if (s.indexof("ABCDEFGHIJKLMNOPQRSTUVWXYZ"; c)>=0) {
        s.add(cb; c)
      }
    };
    let cw=s.build(cb);
    if (s.len(cw)>0) {
      cleanWords=cleanWords.append(cw)
    }
  };
  let found=mut.@($str);
  lp (let i=0; i<taboos.len(); i=i+1) {
    let tb=taboos.get(i);
    let tbUp=s.upper(tb);
    let isFound=mut.false;
    lp (let k=0; k<cleanWords.len(); k=k+1) {
      let cw=cleanWords.get(k);
      if (s.len(cw)==s.len(tbUp)&&s.indexof(cw; tbUp)==0&&s.indexof(tbUp; cw)==0) {
        isFound=true
      }
    };
    if (isFound) {
      found=found.append(tb)
    }
  };
  if (found.len()==0) {
    io.println("Pass")
  } el {
    lp (let i=0; i<found.len(); i=i+1) {
      io.println("Taboo: \(found.get(i))")
    }
  };
  <0
}
