(* source: bench/programs/prime_sieve.tk sha256 8d7a10ce9282f80f250ea7612da02a04db458bc6ed8f83e3b71c163eb5a94b32 *)
m=bench;
f=isprime(n:i64):i64{
  if(n<2){<0}el{
    let d=mut.2;
    let found=mut.1;
    lp(let dummy=0;d*d<n+1;dummy=0){
      if(n-n/d*d==0){
        found=0;
        d=n
      }el{
        d=d+1
      }
    };
    <found
  }
};
f=main():i64{
  let count=mut.0;
  lp(let i=2;i<50000;i=i+1){
    count=count+isprime(i)
  };
  <count
};
