#!/usr/bin/env python3
"""gen_stdlib_decls.py — Auto-generate LLVM IR declarations for all stdlib glue functions.

Scans src/stdlib/*_glue.c and src/stdlib/io_glue.c for function definitions
matching `<rettype> tk_*(<params>) {` and generates a C header with the
g_stdlib_decls entries.

Output: src/stdlib_decls_gen.h (included by llvm.c)

Usage:
    python3 scripts/gen_stdlib_decls.py
    # Then rebuild: make
"""

import os
import re
import sys
from pathlib import Path

TOKE_DIR = Path(__file__).resolve().parent.parent
STDLIB_DIR = TOKE_DIR / "src" / "stdlib"
OUTPUT = TOKE_DIR / "src" / "stdlib_decls_gen.h"

# Map C types to LLVM IR types
TYPE_MAP = {
    "int64_t": "i64",
    "int": "i32",
    "void": "void",
    "double": "double",
    "float": "float",
    "uint64_t": "i64",
    "int32_t": "i32",
    "uint32_t": "i32",
    "int16_t": "i16",
    "uint16_t": "i16",
    "int8_t": "i8",
    "uint8_t": "i8",
    "size_t": "i64",
    "char": "i8",
}


def parse_param_type(param: str) -> str | None:
    """Extract LLVM type from a C parameter declaration."""
    param = param.strip()
    if not param or param == "void":
        return None
    # Remove const
    param = param.replace("const ", "").strip()
    # Check for pointer
    if "*" in param:
        return "i64"  # all pointers are i64 in toke ABI
    # Extract the base type (first word)
    parts = param.split()
    base = parts[0]
    return TYPE_MAP.get(base, "i64")  # default to i64


def parse_function(line: str) -> dict | None:
    """Parse a function definition line into (name, ret_type, param_types)."""
    # Match: <rettype> tk_<name>(<params>) {
    m = re.match(
        r'^(int64_t|void|double|float|uint64_t|int32_t|int)\s+'
        r'(tk_\w+)\s*\(([^)]*)\)\s*\{?\s*$',
        line.strip()
    )
    if not m:
        return None

    ret_c = m.group(1)
    name = m.group(2)
    params_str = m.group(3).strip()

    ret_llvm = TYPE_MAP.get(ret_c, "i64")

    if not params_str or params_str == "void":
        param_types = []
    else:
        params = params_str.split(",")
        param_types = []
        for p in params:
            pt = parse_param_type(p)
            if pt:
                param_types.append(pt)

    return {
        "name": name,
        "ret": ret_llvm,
        "params": param_types,
    }


def scan_glue_files() -> list[dict]:
    """Scan all glue files for tk_* function definitions."""
    functions = []
    seen = set()

    glue_files = sorted(STDLIB_DIR.glob("*_glue.c"))
    # Also check io_glue.c explicitly
    io_glue = STDLIB_DIR / "io_glue.c"
    if io_glue.exists() and io_glue not in glue_files:
        glue_files.append(io_glue)

    # Also scan other .c files in stdlib for tk_* functions
    for f in sorted(STDLIB_DIR.glob("*.c")):
        if f not in glue_files:
            glue_files.append(f)

    for path in glue_files:
        with open(path) as f:
            for line in f:
                fn = parse_function(line)
                if fn and fn["name"] not in seen:
                    fn["source"] = path.name
                    functions.append(fn)
                    seen.add(fn["name"])

    return functions


def load_manual_decls() -> set:
    """Read existing manual declarations from llvm.c to avoid duplicates."""
    llvm_path = TOKE_DIR / "src" / "llvm.c"
    if not llvm_path.exists():
        return set()
    manual = set()
    with open(llvm_path) as f:
        for line in f:
            # Match: {"tk_name", "declare ...", N},
            m = re.match(r'\s*\{"(tk_\w+)",\s*"declare', line)
            if m:
                manual.add(m.group(1))
    return manual


def generate_header(functions: list[dict], exclude: set) -> str:
    """Generate the C header with g_stdlib_decls entries."""
    filtered = [fn for fn in functions if fn["name"] not in exclude]
    lines = [
        "/* stdlib_decls_gen.h — AUTO-GENERATED by scripts/gen_stdlib_decls.py",
        " * Do not edit manually. Regenerate with: python3 scripts/gen_stdlib_decls.py",
        f" * Generated: {len(filtered)} declarations ({len(functions)} scanned, {len(functions)-len(filtered)} skipped as already in llvm.c).",
        " */",
        "",
    ]

    for fn in sorted(filtered, key=lambda f: f["name"]):
        param_str = ", ".join(fn["params"]) if fn["params"] else ""
        decl = f"declare {fn['ret']} @{fn['name']}({param_str})"
        lines.append(f'    {{"{fn["name"]}", "{decl}", 0}},')

    return "\n".join(lines) + "\n"


def main():
    functions = scan_glue_files()
    print(f"Scanned {len(functions)} tk_* functions from stdlib")

    manual = load_manual_decls()
    print(f"Excluding {len(manual)} already declared in llvm.c")

    header = generate_header(functions, manual)
    OUTPUT.write_text(header)
    print(f"Written to {OUTPUT}")

    # Also print stats by source file
    from collections import Counter
    by_source = Counter(fn["source"] for fn in functions)
    for source, count in by_source.most_common():
        print(f"  {source}: {count}")


if __name__ == "__main__":
    main()
