m=bubblesort;
i=io:std.io;
f=bubblesort(arr:@i64):@i64{
  let r=mut.arr;
  let n=r.len;
  lp(let i=0;i<n;i=i+1){
    lp(let j=0;j<n-1-i;j=j+1){
      if(r.get(j)>r.get(j+1)){
        let tmp=r.get(j);
        r=r.set(j;r.get(j+1));
        r=r.set(j+1;tmp);
      };
    };
  };
  <r
};
f=fmt(arr:@i64):str{
  let out=mut."";
  lp(let i=0;i<arr.len;i=i+1){
    out=if(i==0){"\(arr.get(i))"}el{"\(out) \(arr.get(i))"};
  };
  <out
};
f=main():i64{
  io.println(fmt(bubblesort(@(5;2;8;1;9))));
  io.println(fmt(bubblesort(@(3;1;2))));
  io.println(fmt(bubblesort(@())));
  <0
};
